# The path to the (optional) KeyPass install folder
# settign this parameter will enable the option to use the keepass when prompted for the vault tokens
kps_path: ''
kps_writeback_group: 'History'
kps_writeback_history_group: 'Vault - PROD'

# AWS settings
aws_s3_role: 's3'
aws_dynamo_role: 'dynamo'

#Number of keys required to use 
vault_key_quorum: 3

# Vault environments
# list the names and addressess of the vault environments you're using
vault_envs:
  Vault - PROD: ''
'