# The path to the (optional) KeyPass install folder
# setting this parameter will enable the option to use the keepass when prompted for the vault tokens
kps_path: ''
kps_writeback_group: 'History'
kps_writeback_history_groups: ['Vault - PROD']
